# DB나 포트 정보처럼 프로덕션(prod)와 다르게 실행되는 정보
spring.config.import=optional:file:.env.dev[.properties]
server.port=8080
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# 개발 환경에서 테스트나 디버깅 등을 위해서 필요한 사항
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
# SQL 로그를 출력 (실제 운영환경에서는 권장 X)